server:
  port: 8901
  servlet:
    context-path: /base

spring:
  data:
     mongodb:
       uri: mongodb+srv://mybase:xKV3J2vm9177@cluster0.1w14j.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
       database: dashBoard
